// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTky_scfZZP9kAqSY4CPJ7C5PfUPQMHIw',
    appId: '1:437670258252:web:e0e7b872b039b5e4ccf6e9',
    messagingSenderId: '437670258252',
    projectId: 'new-flutter-chatting-app-292ce',
    authDomain: 'new-flutter-chatting-app-292ce.firebaseapp.com',
    storageBucket: 'new-flutter-chatting-app-292ce.appspot.com',
    measurementId: 'G-GGPCZFJN08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvkNWZZH83MJNcYycMjg_vlRdsBQhFxtY',
    appId: '1:437670258252:android:ca900bfee3ec5716ccf6e9',
    messagingSenderId: '437670258252',
    projectId: 'new-flutter-chatting-app-292ce',
    storageBucket: 'new-flutter-chatting-app-292ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzZbL4Nkv6Z90riW-zvi83DoiOAZ7oxx4',
    appId: '1:437670258252:ios:ade19a245a6635aaccf6e9',
    messagingSenderId: '437670258252',
    projectId: 'new-flutter-chatting-app-292ce',
    storageBucket: 'new-flutter-chatting-app-292ce.appspot.com',
    iosClientId: '437670258252-jm5rejvvpcd22ua757qb0bjf9d2t1scu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzZbL4Nkv6Z90riW-zvi83DoiOAZ7oxx4',
    appId: '1:437670258252:ios:ade19a245a6635aaccf6e9',
    messagingSenderId: '437670258252',
    projectId: 'new-flutter-chatting-app-292ce',
    storageBucket: 'new-flutter-chatting-app-292ce.appspot.com',
    iosClientId: '437670258252-jm5rejvvpcd22ua757qb0bjf9d2t1scu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChattingApp',
  );
}
